version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sieg
      MONGO_INITDB_ROOT_PASSWORD: siegdevelop
    ports:
      - "27017:27017"
    volumes:
      - mongo-local:/data/db:rw

# makes sure to not delete the volume
volumes:
  mongo-local:
    external: false
