version: "2.4"

services:
  postgres:
    image: "postgres:14"
    restart: "unless-stopped"
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=sieg
      - POSTGRES_PASSWORD=sieg
    mem_limit: 512m
    volumes:
      - /Users/siegfred/Sorna/container-store/postgres:/var/lib/postgresql/data

    